language: node_js
notifications:
  email: false
node_js:
  - "7"
cache: yarn
script:
  - yarn run lint
  - yarn run test
  - yarn run webpack
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
